; ESP A — "AVIÃO": sensores, fusão de atitude, envio ESP-NOW, OLED de status
[env:aircraft]
platform      = espressif32 @ ^6.9.0
board         = nodemcu-32s
framework     = arduino
monitor_speed = 115200
upload_speed  = 921600
; Defina a porta da Placa A (ver Gerenciador de Dispositivos):
; upload_port  = COM3
; monitor_port = COM3

build_flags =
    -I ../shared/include
    -D CORE_DEBUG_LEVEL=3

lib_deps =
    electroniccats/MPU6050 @ ^1.4.1          ; IMU (acesso ao pino INT e DLPF)
    adafruit/Adafruit BME280 Library @ ^2.2.4
    mprograms/QMC5883LCompass @ ^1.2.3       ; GY-273 (QMC5883L — confirmar chip no I2C scan)
    olikraus/U8g2 @ ^2.35.19                 ; OLED 0,91" SSD1306 128x32

[env:native]
; Testes de lógica pura (fusão, calibração) rodando no PC: pio test -e native
platform    = native
build_flags = -I ../shared/include
test_build_src = no
