; ESP B — "ESTAÇÃO DE SOLO": recebe ESP-NOW, TFT/OLED, encoder, alarmes, AP Wi-Fi + WebSocket
[platformio]
; Página web fica fora do firmware, em ground-station/web (pio run -e ground -t uploadfs)
data_dir = ../../ground-station/web

[env:ground]
platform      = espressif32 @ ^6.9.0
board         = nodemcu-32s
framework     = arduino
monitor_speed = 115200
upload_speed  = 921600
board_build.filesystem = littlefs
; upload_port  = COM4
; monitor_port = COM4

build_flags =
    -I ../shared/include
    -D CORE_DEBUG_LEVEL=3
    ; ---- TFT_eSPI configurado aqui (não editar a lib) ----
    -D USER_SETUP_LOADED=1
    -D ST7789_DRIVER=1
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=240          ; ajustar conforme o módulo (240x240 ou 240x320)
    -D TFT_MOSI=23
    -D TFT_SCLK=18
    -D TFT_CS=5                ; -1 se o módulo não tiver pino CS
    -D TFT_DC=16
    -D TFT_RST=17
    -D TFT_BL=4
    -D TFT_BACKLIGHT_ON=HIGH
    -D LOAD_GLCD=1
    -D LOAD_FONT2=1
    -D LOAD_FONT4=1
    -D SMOOTH_FONT=1
    -D SPI_FREQUENCY=40000000

lib_deps =
    bodmer/TFT_eSPI @ ^2.5.43                 ; TFT + sprites (desenho sem flicker)
    olikraus/U8g2 @ ^2.35.19                  ; OLED 0,96" 128x64
    links2004/WebSockets @ ^2.6.1             ; servidor WebSocket :81
    bblanchon/ArduinoJson @ ^7.2.0

[env:native]
platform    = native
build_flags = -I ../shared/include
test_build_src = no
